### ISSUE TITLE
_reload() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by skycloud1030** [Kitware/trame-vuetify#3]
https://github.com/Kitware/trame-vuetify/blob/master/trame_vuetify/ui/vuetify.py#L115

> self.server.controller.on_server_reload(self.server)

https://github.com/Kitware/paraview-visualizer/blob/master/pv_visualizer/app/ui/main.py#L21
> def _reload():

They are several event listener `on_server_reload` didn't have argument in `paraview-visualizer` makes the reload didn't works.

Is argument `self.server` necessary?

**Comment by jourdain** [comment]
It is paraview-visualizer that should update its API expectation. That was added on purpose.
