### ISSUE TITLE
VAppBar app property deprecated in Vuetify 3

### ISSUE THREAD

**Issue by landynfrancis** [Kitware/trame-vuetify#4]
**Describe the bug**
In `trame.ui.vuetify3`, there are the predefined Layouts such as `SinglePageLayout`. For example, in the definition of the VAppBar there is a parameter `app=True`. However, in vuetify3, this property was removed. See [Vuetify3 API](https://vuetifyjs.com/en/api/v-app-bar/#links). As it stands, this parameter seemingly does nothing, yet it is used throughout the SinglePageLayout class.

https://github.com/Kitware/trame-vuetify/blob/72a960214be0d16ac0e9c7f24a6a447985d0f0c2/trame_vuetify/ui/vuetify.py#L67-L69
https://github.com/Kitware/trame-vuetify/blob/72a960214be0d16ac0e9c7f24a6a447985d0f0c2/trame_vuetify/ui/vuetify.py#L72-L74
https://github.com/Kitware/trame-vuetify/blob/72a960214be0d16ac0e9c7f24a6a447985d0f0c2/trame_vuetify/ui/vuetify3.py#L71-L73
https://github.com/Kitware/trame-vuetify/blob/72a960214be0d16ac0e9c7f24a6a447985d0f0c2/trame_vuetify/ui/vuetify3.py#L79-L81

**To Reproduce**

N/A

***Code***

N/A

**Expected behavior**

N/A

**Screenshots**

N/A

**Platform:**

***Device:***

- [x] Desktop
- [ ] Mobile

***OS:***

- [ ] Windows
- [ ] MacOS
- [x] Linux
- [ ] Android
- [ ] iOS

***Browsers Affected:***

- [x] Chrome
- [ ] Firefox
- [ ] Microsoft Edge
- [ ] Safari
- [ ] Opera
- [ ] Brave
- [ ] IE 11

**Comment by jourdain** [comment]
Thanks for the report. Feel free to provide a PR with a better usage of the vuetify3 API. As you've noticed, it was almost picked up as-is from our vuetify2 one.

**Comment by landynfrancis** [comment]
I'm not very experienced with the vuetify API, I could make a PR to just remove the app=True, but I'm not sure how the behavior of having app=True would be accomplished in Vuetify3.

**Comment by jourdain** [comment]
Ok don't worry about it then. We will eventually clean that piece of code. What is happening is those args, just get ignored.

**Comment by jourdain** [comment]
fixed in 2.4.0
