### ISSUE TITLE
I didn't understand the syntax of trame-vue

### ISSUE THREAD

**Issue by MarinsLucas** [Kitware/trame-vuetify#6]
Hi, I'm trying to create a dropdown for my project, so I found the VSelect component in vuetifty website. 

https://vuetifyjs.com/en/components/menus/#api

How can I create this component in trame-vuetify?

**Comment by jourdain** [comment]
https://trame.readthedocs.io/en/latest/trame.widgets.vuetify3.html

**Comment by jourdain** [comment]
Closing since it is not an issue with the library
